name: A Finite View
description: A blog of things by Micah Denbraver.
author: Micah Denbraver
url: http://micah.bigprob.net
permalink: /:categories/:year/:title.html
paginate: 5
exclude: [CNAME, Gemfile, Gemfile.lock]
